### ISSUE TITLE
Plans to switch to Swift Package Manager?

### ISSUE THREAD

**Issue by brettfazio** [magiclabs/magic-ios-pod#13]
I was wondering if there are plans to switch over the iOS SDK from CocoaPods to SPM.

I know it's compiled as a framework right now so it would require some changes to the repository, but is the idea on the horizon?

**Comment by Ethella** [comment]
@brettfazio We have tried SPM when Xcode 14 was out, but we found some blockers during migration. I think we'll make another attempt for sure but I can't say when.

**Comment by mirkokiefer** [comment]
@Ethella would you consider open-sourcing the iOS SDK - community might be able to help with porting to SPM. No SPM support is a blocker for us to adopt Magic.

**Comment by Ethella** [comment]
> @Ethella would you consider open-sourcing the iOS SDK - community might be able to help with porting to SPM. No SPM support is a blocker for us to adopt Magic.

I'll bring this to the team, and we will discuss it. 😃

**Comment by arturoreyes93** [comment]
Any updates on this? Our team is also interested in partnering with you but not having SPM support is an issue.

**Comment by Ethella** [comment]
@arturoreyes93 Good news is we are considering to open-source our iOS library, which SPM will be included for sure, but the date is TBD

**Comment by Ryce** [comment]
Hey guys, +1 on this. Our project does not support CocoaPods, and frankly a whole year to add SPM is a bit crazy

**Comment by Ethella** [comment]
For anyone who's waiting for SPM support, Here's a quick update to this. 

We've been working on this over the week and the original plan is to get `MagicSDK.xcframework` distributed on SPM first to let everyone start working on it. However, due to the lack of support for transitive dependencies using XCframework in SPM, we encounter some sub dependencies missing errors, which requires a significant effort for us to address this. 
![image](https://user-images.githubusercontent.com/33166884/149648604-d2ec4544-3539-4981-883d-2ebb2c92ac64.png)

For more context about this error please check, https://forums.swift.org/t/issue-with-third-party-dependencies-inside-a-xcframework-through-spm/41977. If anyone has experience with this, feel free to leave your comments here. any help will be welcomed.

Therefore, the other optimal solution is to open-source `MagicSDK`, which will unblock the error and accelerate the process. It will take us a few days to audit the codebase and I'll keep posting updates here. 😄

**Comment by Ethella** [comment]
SPM has been supported!

https://github.com/magiclabs/magic-ios
https://github.com/magiclabs/magic-ios-ext
